//+------------------------------------------------------------------+
//|                                    SMT_Trap_Pro.mq5              |
//|                        Smart Money Trap Strategy v1.0             |
//|                   Generated by Trading Strategy AI Platform        |
//|              Liquidity Sweep + Order Block Confirmation            |
//+------------------------------------------------------------------+
#property copyright "Trading Strategy AI Platform"
#property link      "https://github.com/crazycompanyinc/trading-strategy-ai-platform"
#property version   "1.00"
#property description "Smart Money Trap: Liquidity Sweep + Order Block"
#property description "Detects institutional stop hunts and enters at OB zones"
#property strict

#include <Trade\Trade.mqh>
#include <Trade\PositionInfo.mqh>
#include <Trade\SymbolInfo.mqh>

//+------------------------------------------------------------------+
//| Input Parameters                                                  |
//+------------------------------------------------------------------+
input group "=== Risk Management ==="
input double   InpStopLoss      = 30;       // Stop Loss (pips)
input double   InpTakeProfit    = 60;       // Take Profit (pips)
input double   InpRiskPercent   = 1.0;      // Risk per Trade (%)
input double   InpLotSize       = 0.1;      // Fixed Lot Size (0=auto)
input int      InpMagicNumber   = 777888;   // Magic Number
input int      InpSlippage      = 10;       // Slippage (points)

input group "=== ICT Detection Parameters ==="
input int      InpSwingLookback = 3;        // Swing Point Lookback (bars)
input int      InpOBLookback    = 10;       // Order Block Lookback (count)
input int      InpLiquidityLookback = 200;  // Liquidity Sweep Lookback (bars)
input double   InpSweepThreshold = 0.0005;  // Sweep Threshold (price ratio)
input int      InpMaxBarsHeld   = 30;       // Max Bars Held (time exit)

input group "=== Trend Filter ==="
input bool     InpUseTrendFilter = true;    // Use EMA Trend Filter
input int      InpEMAFast       = 50;       // Fast EMA Period
input int      InpEMASlow       = 200;      // Slow EMA Period

input group "=== Trading Hours ==="
input bool     InpUseTradingHours = true;   // Use Trading Hours Filter
input int      InpStartHour     = 8;        // Trading Start Hour (server time)
input int      InpEndHour       = 20;       // Trading End Hour (server time)

//+------------------------------------------------------------------+
//| Indicator Handles                                                 |
//+------------------------------------------------------------------+
int h_ema_fast = INVALID_HANDLE;
int h_ema_slow = INVALID_HANDLE;

//+------------------------------------------------------------------+
//| Global Variables                                                  |
//+------------------------------------------------------------------+
CTrade         trade;
CPositionInfo  posInfo;
CSymbolInfo    symInfo;
datetime       lastBarTime = 0;

// Swing point tracking
double         swingHighs[][2];  // [price, bar_index]
double         swingLows[][2];
int            swingCount = 0;

// Order Block tracking
double         obBullish[][3];   // [high, low, bar_index]
double         obBearish[][3];
int            obBullCount = 0;
int            obBearCount = 0;

//+------------------------------------------------------------------+
//| Expert initialization function                                    |
//+------------------------------------------------------------------+
int OnInit()
{
   trade.SetExpertMagicNumber(InpMagicNumber);
   trade.SetDeviationInPoints(InpSlippage);
   trade.SetTypeFilling(ORDER_FILLING_IOC);
   symInfo.Name(_Symbol);

   h_ema_fast = iMA(_Symbol, PERIOD_CURRENT, InpEMAFast, 0, MODE_EMA, PRICE_CLOSE);
   h_ema_slow = iMA(_Symbol, PERIOD_CURRENT, InpEMASlow, 0, MODE_EMA, PRICE_CLOSE);

   if(h_ema_fast == INVALID_HANDLE || h_ema_slow == INVALID_HANDLE)
   {
      Print("ERROR: Failed to create EMA indicators");
      return INIT_FAILED;
   }

   Print("SMT Trap Pro initialized on ", _Symbol, " | SL:", InpStopLoss, " TP:", InpTakeProfit);
   return INIT_SUCCEEDED;
}

//+------------------------------------------------------------------+
//| Expert deinitialization function                                  |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
{
   if(h_ema_fast != INVALID_HANDLE) IndicatorRelease(h_ema_fast);
   if(h_ema_slow != INVALID_HANDLE) IndicatorRelease(h_ema_slow);
   ChartRedraw();
}

//+------------------------------------------------------------------+
//| Expert tick function                                              |
//+------------------------------------------------------------------+
void OnTick()
{
   // Check for new bar
   datetime currentBarTime = iTime(_Symbol, PERIOD_CURRENT, 0);
   if(currentBarTime == lastBarTime) return;
   lastBarTime = currentBarTime;

   // Refresh symbol info
   symInfo.RefreshRates();

   // Check trading hours
   if(InpUseTradingHours && !IsTradingHour()) return;

   // Get indicator values
   double emaFast[], emaSlow[];
   ArraySetAsSeries(emaFast, true);
   ArraySetAsSeries(emaSlow, true);
   if(CopyBuffer(h_ema_fast, 0, 0, 3, emaFast) <= 0) return;
   if(CopyBuffer(h_ema_slow, 0, 0, 3, emaSlow) <= 0) return;

   // Get price data
   double close[], high[], low[], open[];
   ArraySetAsSeries(close, true);
   ArraySetAsSeries(high, true);
   ArraySetAsSeries(low, true);
   ArraySetAsSeries(open, true);
   if(CopyClose(_Symbol, PERIOD_CURRENT, 0, InpLiquidityLookback + 10, close) <= 0) return;
   if(CopyHigh(_Symbol, PERIOD_CURRENT, 0, InpLiquidityLookback + 10, high) <= 0) return;
   if(CopyLow(_Symbol, PERIOD_CURRENT, 0, InpLiquidityLookback + 10, low) <= 0) return;
   if(CopyOpen(_Symbol, PERIOD_CURRENT, 0, InpLiquidityLookback + 10, open) <= 0) return;

   int totalBars = ArraySize(close);

   // Detect ICT concepts
   bool isBullishSweep = DetectBullishLiquiditySweep(high, low, close, totalBars);
   bool isBearishSweep = DetectBearishLiquiditySweep(high, low, close, totalBars);
   bool isBullishOB = DetectPriceAtBullishOB(high, low, close, totalBars);
   bool isBearishOB = DetectPriceAtBearishOB(high, low, close, totalBars);
   bool isBullishCHoCH = DetectBullishCHoCH(high, low, close, totalBars);
   bool isBearishCHoCH = DetectBearishCHoCH(high, low, close, totalBars);

   // Check existing position
   bool hasPosition = false;
   bool isLong = false;
   int barsHeld = 0;
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      if(posInfo.SelectByIndex(i) && posInfo.Magic() == InpMagicNumber)
      {
         hasPosition = true;
         isLong = posInfo.PositionType() == POSITION_TYPE_BUY;
         barsHeld = (int)((TimeCurrent() - posInfo.Time()) / PeriodSeconds());
         break;
      }
   }

   // ── EXIT LOGIC ──
   if(hasPosition)
   {
      bool shouldExit = false;

      // Time-based exit
      if(barsHeld >= InpMaxBarsHeld) shouldExit = true;

      // CHoCH exit signal
      if(isLong && isBearishCHoCH) shouldExit = true;
      if(!isLong && isBullishCHoCH) shouldExit = true;

      // BOS exit signal
      if(isLong && DetectBearishBOS(high, low, close, totalBars)) shouldExit = true;
      if(!isLong && DetectBullishBOS(high, low, close, totalBars)) shouldExit = true;

      if(shouldExit)
      {
         trade.PositionClose(_Symbol);
         return;
      }

      // Trailing stop
      ApplyTrailingStop(isLong);
   }

   // ── ENTRY LOGIC ──
   if(!hasPosition)
   {
      // Trend filter
      bool trendOK = true;
      if(InpUseTrendFilter)
      {
         // For bullish: price above slow EMA, fast EMA above slow EMA
         // For bearish: price below slow EMA, fast EMA below slow EMA
         // We check both directions
      }

      // BUY: Bullish Liquidity Sweep + Bullish Order Block
      if(isBullishSweep && isBullishOB)
      {
         if(!InpUseTrendFilter || (close[1] > emaSlow[1] && emaFast[1] > emaSlow[1]))
         {
            OpenBuy();
            return;
         }
      }

      // SELL: Bearish Liquidity Sweep + Bearish Order Block
      if(isBearishSweep && isBearishOB)
      {
         if(!InpUseTrendFilter || (close[1] < emaSlow[1] && emaFast[1] < emaSlow[1]))
         {
            OpenSell();
            return;
         }
      }
   }
}

//+------------------------------------------------------------------+
//| Detect Bullish Liquidity Sweep (stop hunt below swing low)        |
//+------------------------------------------------------------------+
bool DetectBullishLiquiditySweep(double &high[], double &low[], double &close[], int totalBars)
{
   int lookback = MathMin(InpLiquidityLookback, totalBars - 10);

   // Find the lowest swing low in lookback period
   double lowestLow = DBL_MAX;
   int lowestBar = -1;

   for(int i = 2; i < lookback; i++)
   {
      // Check if this is a swing low
      bool isSwingLow = true;
      for(int j = 1; j <= InpSwingLookback; j++)
      {
         if(i + j >= totalBars) { isSwingLow = false; break; }
         if(low[i] > low[i-j] || low[i] > low[i+j]) { isSwingLow = false; break; }
      }
      if(isSwingLow && low[i] < lowestLow)
      {
         lowestLow = low[i];
         lowestBar = i;
      }
   }

   if(lowestBar < 0) return false;

   // Check if current bar swept below the lowest low but closed above
   if(low[1] < lowestLow && close[1] > lowestLow)
      return true;

   // Alternative: price touched the level and reversed with momentum
   if(MathAbs(low[1] - lowestLow) / lowestLow < InpSweepThreshold)
   {
      if(close[1] > open[1]) // Bullish candle
      {
         double body = close[1] - open[1];
         double range = high[1] - low[1];
         if(range > 0 && body / range > 0.4) return true;
      }
   }

   return false;
}

//+------------------------------------------------------------------+
//| Detect Bearish Liquidity Sweep (stop hunt above swing high)       |
//+------------------------------------------------------------------+
bool DetectBearishLiquiditySweep(double &high[], double &low[], double &close[], int totalBars)
{
   int lookback = MathMin(InpLiquidityLookback, totalBars - 10);

   double highestHigh = 0;
   int highestBar = -1;

   for(int i = 2; i < lookback; i++)
   {
      bool isSwingHigh = true;
      for(int j = 1; j <= InpSwingLookback; j++)
      {
         if(i + j >= totalBars) { isSwingHigh = false; break; }
         if(high[i] < high[i-j] || high[i] < high[i+j]) { isSwingHigh = false; break; }
      }
      if(isSwingHigh && high[i] > highestHigh)
      {
         highestHigh = high[i];
         highestBar = i;
      }
   }

   if(highestBar < 0) return false;

   if(high[1] > highestHigh && close[1] < highestHigh)
      return true;

   if(MathAbs(high[1] - highestHigh) / highestHigh < InpSweepThreshold)
   {
      if(close[1] < open[1])
      {
         double body = open[1] - close[1];
         double range = high[1] - low[1];
         if(range > 0 && body / range > 0.4) return true;
      }
   }

   return false;
}

//+------------------------------------------------------------------+
//| Detect Price at Bullish Order Block                               |
//+------------------------------------------------------------------+
bool DetectPriceAtBullishOB(double &high[], double &low[], double &close[], int totalBars)
{
   int lookback = MathMin(InpOBLookback * 10, totalBars - 10);

   for(int i = 3; i < lookback; i++)
   {
      // Bullish OB: bearish candle followed by 2+ bullish candles
      if(close[i] < open[i]) // Bearish candle
      {
         int followUp = 0;
         for(int j = 1; j <= 3; j++)
         {
            if(i - j < 0) break;
            if(close[i-j] > open[i-j]) followUp++;
         }
         if(followUp >= 2)
         {
            double obHigh = high[i];
            double obLow = low[i];

            // Check if current price is interacting with this OB
            if((low[1] <= obHigh && low[1] >= obLow) ||
               (close[1] <= obHigh && close[1] >= obLow) ||
               (low[1] <= obLow && close[1] >= obHigh))
            {
               return true;
            }
         }
      }
   }
   return false;
}

//+------------------------------------------------------------------+
//| Detect Price at Bearish Order Block                               |
//+------------------------------------------------------------------+
bool DetectPriceAtBearishOB(double &high[], double &low[], double &close[], int totalBars)
{
   int lookback = MathMin(InpOBLookback * 10, totalBars - 10);

   for(int i = 3; i < lookback; i++)
   {
      if(close[i] > open[i]) // Bullish candle
      {
         int followDown = 0;
         for(int j = 1; j <= 3; j++)
         {
            if(i - j < 0) break;
            if(close[i-j] < open[i-j]) followDown++;
         }
         if(followDown >= 2)
         {
            double obHigh = high[i];
            double obLow = low[i];

            if((low[1] <= obHigh && low[1] >= obLow) ||
               (close[1] <= obHigh && close[1] >= obLow) ||
               (low[1] <= obLow && close[1] >= obHigh))
            {
               return true;
            }
         }
      }
   }
   return false;
}

//+------------------------------------------------------------------+
//| Detect Bullish CHoCH (Change of Character)                        |
//+------------------------------------------------------------------+
bool DetectBullishCHoCH(double &high[], double &low[], double &close[], int totalBars)
{
   // CHoCH: after lower lows, price breaks above a swing high
   if(totalBars < 20) return false;

   double recentLL = DBL_MAX;
   double prevLL = DBL_MAX;
   double recentSH = 0;

   for(int i = 2; i < 50 && i < totalBars; i++)
   {
      bool isSL = true;
      for(int j = 1; j <= InpSwingLookback; j++)
      {
         if(i + j >= totalBars) { isSL = false; break; }
         if(low[i] > low[i-j] || low[i] > low[i+j]) { isSL = false; break; }
      }
      if(isSL)
      {
         if(low[i] < recentLL) { prevLL = recentLL; recentLL = low[i]; }
      }

      bool isSH = true;
      for(int j = 1; j <= InpSwingLookback; j++)
      {
         if(i + j >= totalBars) { isSH = false; break; }
         if(high[i] < high[i-j] || high[i] < high[i+j]) { isSH = false; break; }
      }
      if(isSH && high[i] > recentSH) { recentSH = high[i]; }
   }

   if(prevLL != DBL_MAX && recentLL < prevLL && close[1] > recentSH)
      return true;

   return false;
}

//+------------------------------------------------------------------+
//| Detect Bearish CHoCH                                              |
//+------------------------------------------------------------------+
bool DetectBearishCHoCH(double &high[], double &low[], double &close[], int totalBars)
{
   if(totalBars < 20) return false;

   double recentHH = 0;
   double prevHH = 0;
   double recentSL = DBL_MAX;

   for(int i = 2; i < 50 && i < totalBars; i++)
   {
      bool isSH = true;
      for(int j = 1; j <= InpSwingLookback; j++)
      {
         if(i + j >= totalBars) { isSH = false; break; }
         if(high[i] < high[i-j] || high[i] < high[i+j]) { isSH = false; break; }
      }
      if(isSH)
      {
         if(high[i] > recentHH) { prevHH = recentHH; recentHH = high[i]; }
      }

      bool isSL = true;
      for(int j = 1; j <= InpSwingLookback; j++)
      {
         if(i + j >= totalBars) { isSL = false; break; }
         if(low[i] > low[i-j] || low[i] > low[i+j]) { isSL = false; break; }
      }
      if(isSL && low[i] < recentSL) { recentSL = low[i]; }
   }

   if(prevHH > 0 && recentHH > prevHH && close[1] < recentSL)
      return true;

   return false;
}

//+------------------------------------------------------------------+
//| Detect Bullish BOS (Break of Structure)                           |
//+------------------------------------------------------------------+
bool DetectBullishBOS(double &high[], double &low[], double &close[], int totalBars)
{
   if(totalBars < 10) return false;

   double lastSH = 0;
   for(int i = 2; i < 30 && i < totalBars; i++)
   {
      bool isSH = true;
      for(int j = 1; j <= InpSwingLookback; j++)
      {
         if(i + j >= totalBars) { isSH = false; break; }
         if(high[i] < high[i-j] || high[i] < high[i+j]) { isSH = false; break; }
      }
      if(isSH) { lastSH = high[i]; break; }
   }

   if(lastSH > 0 && close[1] > lastSH) return true;
   return false;
}

//+------------------------------------------------------------------+
//| Detect Bearish BOS                                                |
//+------------------------------------------------------------------+
bool DetectBearishBOS(double &high[], double &low[], double &close[], int totalBars)
{
   if(totalBars < 10) return false;

   double lastSL = DBL_MAX;
   for(int i = 2; i < 30 && i < totalBars; i++)
   {
      bool isSL = true;
      for(int j = 1; j <= InpSwingLookback; j++)
      {
         if(i + j >= totalBars) { isSL = false; break; }
         if(low[i] > low[i-j] || low[i] > low[i+j]) { isSL = false; break; }
      }
      if(isSL) { lastSL = low[i]; break; }
   }

   if(lastSL != DBL_MAX && close[1] < lastSL) return true;
   return false;
}

//+------------------------------------------------------------------+
//| Apply Trailing Stop                                               |
//+------------------------------------------------------------------+
void ApplyTrailingStop(bool isLong)
{
   double trailPips = InpStopLoss * 0.5; // Trail at half SL distance
   double trailPoints = trailPips * _Point;

   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      if(!posInfo.SelectByIndex(i) || posInfo.Magic() != InpMagicNumber) continue;

      double openPrice = posInfo.PriceOpen();
      double currentSL = posInfo.StopLoss();
      double currentTP = posInfo.TakeProfit();

      if(isLong)
      {
         double newSL = symInfo.Bid() - trailPoints;
         newSL = NormalizeDouble(newSL, _Digits);
         if(newSL > currentSL && newSL < symInfo.Bid() - symInfo.StopsLevel() * _Point)
         {
            trade.PositionModify(posInfo.Ticket(), newSL, currentTP);
         }
      }
      else
      {
         double newSL = symInfo.Ask() + trailPoints;
         newSL = NormalizeDouble(newSL, _Digits);
         if((newSL < currentSL || currentSL == 0) && newSL > symInfo.Ask() + symInfo.StopsLevel() * _Point)
         {
            trade.PositionModify(posInfo.Ticket(), newSL, currentTP);
         }
      }
   }
}

//+------------------------------------------------------------------+
//| Open Buy Position                                                 |
//+------------------------------------------------------------------+
void OpenBuy()
{
   double lotSize = CalculateLotSize();
   double ask = symInfo.Ask();
   double sl = InpStopLoss > 0 ? NormalizeDouble(ask - InpStopLoss * _Point, _Digits) : 0;
   double tp = InpTakeProfit > 0 ? NormalizeDouble(ask + InpTakeProfit * _Point, _Digits) : 0;

   if(trade.Buy(lotSize, _Symbol, ask, sl, tp, "SMT Trap BUY"))
   {
      Print("BUY opened: Lot=", lotSize, " SL=", sl, " TP=", tp);
   }
   else
   {
      Print("BUY failed: ", GetLastError());
   }
}

//+------------------------------------------------------------------+
//| Open Sell Position                                                |
//+------------------------------------------------------------------+
void OpenSell()
{
   double lotSize = CalculateLotSize();
   double bid = symInfo.Bid();
   double sl = InpStopLoss > 0 ? NormalizeDouble(bid + InpStopLoss * _Point, _Digits) : 0;
   double tp = InpTakeProfit > 0 ? NormalizeDouble(bid - InpTakeProfit * _Point, _Digits) : 0;

   if(trade.Sell(lotSize, _Symbol, bid, sl, tp, "SMT Trap SELL"))
   {
      Print("SELL opened: Lot=", lotSize, " SL=", sl, " TP=", tp);
   }
   else
   {
      Print("SELL failed: ", GetLastError());
   }
}

//+------------------------------------------------------------------+
//| Calculate Lot Size Based on Risk                                  |
//+------------------------------------------------------------------+
double CalculateLotSize()
{
   if(InpLotSize > 0) return InpLotSize;
   if(InpRiskPercent <= 0 || InpStopLoss <= 0) return 0.01;

   double accountBalance = AccountInfoDouble(ACCOUNT_BALANCE);
   double riskAmount = accountBalance * InpRiskPercent / 100.0;
   double tickValue = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_VALUE);
   double tickSize = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_SIZE);

   if(tickValue == 0 || tickSize == 0) return 0.01;

   double lotSize = riskAmount / (InpStopLoss * _Point * tickValue / tickSize);
   lotSize = NormalizeDouble(lotSize, 2);

   double minLot = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MIN);
   double maxLot = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MAX);
   double lotStep = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_STEP);

   lotSize = MathMax(minLot, lotSize);
   lotSize = MathMin(maxLot, lotSize);
   lotSize = MathFloor(lotSize / lotStep) * lotStep;

   return lotSize;
}

//+------------------------------------------------------------------+
//| Check Trading Hours                                               |
//+------------------------------------------------------------------+
bool IsTradingHour()
{
   MqlDateTime dt;
   TimeCurrent(dt);
   return (dt.hour >= InpStartHour && dt.hour < InpEndHour);
}
//+------------------------------------------------------------------+
