"""
MT5 Code Generator - Generates MQL5 Expert Advisor code from Strategy IR.
"""
from __future__ import annotations
from typing import Dict, Any, List, Optional


class MT5Generator:
    """
    Generates complete, compilable MQL5 Expert Advisor code
    from a strategy intermediate representation.
    """

    def generate(self, strategy: dict) -> str:
        """
        Generate complete MQL5 code from strategy dict.
        
        Returns complete .mq5 file content.
        """
        name = strategy.get("name", "GeneratedStrategy").replace(" ", "_")
        indicators = strategy.get("indicators", [])
        entries = strategy.get("entry_signals", [])
        exits = strategy.get("exit_signals", [])
        rm = strategy.get("risk_management", {})

        code_parts = []

        # Header
        code_parts.append(self._generate_header(name))

        # Input parameters
        code_parts.append(self._generate_inputs(indicators, rm))

        # Indicator handles and buffers
        code_parts.append(self._generate_indicator_declarations(indicators))

        # Global variables
        code_parts.append(self._generate_globals())

        # OnInit
        code_parts.append(self._generate_on_init(indicators))

        # OnTick
        code_parts.append(self._generate_on_tick(indicators, entries, exits, rm))

        # OnDeinit
        code_parts.append(self._generate_on_deinit())

        # Helper functions
        code_parts.append(self._generate_helper_functions())

        return "\n".join(code_parts)

    def _generate_header(self, name: str) -> str:
        return f"""//+------------------------------------------------------------------+
//|                                          {name}.mq5|
//|                          Generated by Trading Strategy AI Platform |
//|                                     https://github.com/crazycompanyinc|
//+------------------------------------------------------------------+
#property copyright "Trading Strategy AI Platform"
#property link      "https://github.com/crazycompanyinc/trading-strategy-ai-platform"
#property version   "1.00"
#property description "Auto-generated Expert Advisor"
#property strict

#include <Trade\\Trade.mqh>
#include <Trade\\PositionInfo.mqh>
#include <Trade\\SymbolInfo.mqh>
"""

    def _generate_inputs(self, indicators: List[dict], rm: dict) -> str:
        lines = ["//--- Input Parameters"]
        lines.append("input group \"=== Risk Management ===\"")

        if rm.get("stop_loss"):
            lines.append(f"input double   InpStopLoss      = {rm['stop_loss']};    // Stop Loss (points)")
        else:
            lines.append("input double   InpStopLoss      = 50;       // Stop Loss (points)")

        if rm.get("take_profit"):
            lines.append(f"input double   InpTakeProfit    = {rm['take_profit']};   // Take Profit (points)")
        else:
            lines.append("input double   InpTakeProfit    = 100;      // Take Profit (points)")

        if rm.get("risk_per_trade"):
            lines.append(f"input double   InpRiskPercent   = {rm['risk_per_trade']};     // Risk per Trade (%)")
        else:
            lines.append("input double   InpRiskPercent   = 1.0;      // Risk per Trade (%)")

        if rm.get("trailing_stop"):
            lines.append(f"input double   InpTrailingStop  = {rm['trailing_stop']};    // Trailing Stop (points)")

        if rm.get("max_position_size"):
            lines.append(f"input double   InpLotSize       = {rm['max_position_size']};       // Lot Size")
        else:
            lines.append("input double   InpLotSize       = 0.1;       // Lot Size")

        lines.append("input int      InpMagicNumber   = 123456;   // Magic Number")
        lines.append("input int      InpSlippage      = 10;       // Slippage (points)")

        lines.append("")
        lines.append(input_group := "//--- Indicator Parameters")
        for ind in indicators:
            ind_type = ind.get("type", "").lower()
            params = ind.get("parameters", {})
            period = params.get("period", 14)

            if ind_type in ("sma", "ema"):
                lines.append(f"input int      Inp{ind_type.upper()}Period    = {period};      // {ind_type.upper()} Period")
            elif ind_type == "rsi":
                lines.append(f"input int      InpRSIPeriod     = {period};      // RSI Period")
                lines.append(f"input double   InpRSIOverbought = {params.get('overbought', 70)};    // RSI Overbought Level")
                lines.append(f"input double   InpRSIOversold   = {params.get('oversold', 30)};    // RSI Oversold Level")
            elif ind_type == "macd":
                lines.append(f"input int      InpMACDFast      = {params.get('fast_period', 12)};      // MACD Fast Period")
                lines.append(f"input int      InpMACDSlow      = {params.get('slow_period', 26)};      // MACD Slow Period")
                lines.append(f"input int      InpMACDSignal    = {params.get('signal_period', 9)};       // MACD Signal Period")
            elif ind_type in ("bollinger_bands", "bb"):
                lines.append(f"input int      InpBBPeriod      = {period};      // Bollinger Bands Period")
                lines.append(f"input double   InpBBStdDev      = {params.get('std_dev', 2.0)};    // Bollinger Bands Std Dev")
            elif ind_type == "atr":
                lines.append(f"input int      InpATRPeriod     = {period};      // ATR Period")
            elif ind_type == "stochastic":
                lines.append(f"input int      InpStochK        = {period};      // Stochastic %K Period")
                lines.append(f"input int      InpStochD        = 3;       // Stochastic %D Period")
                lines.append(f"input int      InpStochSlowing  = 3;       // Stochastic Slowing")
            elif ind_type == "cci":
                lines.append(f"input int      InpCCIPeriod     = {period};      // CCI Period")
            elif ind_type == "adx":
                lines.append(f"input int      InpADXPeriod     = {period};      // ADX Period")

        return "\n".join(lines) + "\n"

    def _generate_indicator_declarations(self, indicators: List[dict]) -> str:
        lines = ["//--- Indicator Handles"]
        for ind in indicators:
            ind_type = ind.get("type", "").lower()
            handle_name = f"h_{ind_type}"
            lines.append(f"int {handle_name} = INVALID_HANDLE;")

        lines.append("")
        lines.append("//--- Indicator Buffers")
        for ind in indicators:
            ind_type = ind.get("type", "").lower()
            if ind_type in ("sma", "ema"):
                lines.append(f"double {ind_type}Buffer[];")
            elif ind_type == "rsi":
                lines.append("double rsiBuffer[];")
            elif ind_type == "macd":
                lines.append("double macdMainBuffer[];")
                lines.append("double macdSignalBuffer[];")
            elif ind_type in ("bollinger_balls", "bb"):
                lines.append("double bbUpperBuffer[];")
                lines.append("double bbMiddleBuffer[];")
                lines.append("double bbLowerBuffer[];")
            elif ind_type == "atr":
                lines.append("double atrBuffer[];")
            elif ind_type == "stochastic":
                lines.append("double stochKBuffer[];")
                lines.append("double stochDBuffer[];")
            elif ind_type == "cci":
                lines.append("double cciBuffer[];")
            elif ind_type == "adx":
                lines.append("double adxBuffer[];")

        return "\n".join(lines) + "\n"

    def _generate_globals(self) -> str:
        return """
//--- Global Variables
CTrade         trade;
CPositionInfo  posInfo;
CSymbolInfo    symInfo;
datetime       lastBarTime = 0;
"""

    def _generate_on_init(self, indicators: List[dict]) -> str:
        lines = ["//+------------------------------------------------------------------+", "//| Expert initialization function                                   |", "//+------------------------------------------------------------------+"]
        lines.append("int OnInit()")
        lines.append("{")
        lines.append("   trade.SetExpertMagicNumber(InpMagicNumber);")
        lines.append("   trade.SetDeviationInPoints(InpSlippage);")
        lines.append("   trade.SetTypeFill(ORDER_FILLING_IOC);")
        lines.append("   symInfo.Name(_Symbol);")
        lines.append("")

        for ind in indicators:
            ind_type = ind.get("type", "").lower()
            period = ind.get("parameters", {}).get("period", 14)

            if ind_type == "sma":
                lines.append(f"   h_sma = iMA(_Symbol, PERIOD_CURRENT, InpSMAPeriod, 0, MODE_SMA, PRICE_CLOSE);")
                lines.append("   if(h_sma == INVALID_HANDLE) return INIT_FAILED;")
                lines.append("   ArraySetAsSeries(smaBuffer, true);")
            elif ind_type == "ema":
                lines.append(f"   h_ema = iMA(_Symbol, PERIOD_CURRENT, InpEMAPeriod, 0, MODE_EMA, PRICE_CLOSE);")
                lines.append("   if(h_ema == INVALID_HANDLE) return INIT_FAILED;")
                lines.append("   ArraySetAsSeries(emaBuffer, true);")
            elif ind_type == "rsi":
                lines.append(f"   h_rsi = iRSI(_Symbol, PERIOD_CURRENT, InpRSIPeriod, PRICE_CLOSE);")
                lines.append("   if(h_rsi == INVALID_HANDLE) return INIT_FAILED;")
                lines.append("   ArraySetAsSeries(rsiBuffer, true);")
            elif ind_type == "macd":
                lines.append(f"   h_macd = iMACD(_Symbol, PERIOD_CURRENT, InpMACDFast, InpMACDSlow, InpMACDSignal, PRICE_CLOSE);")
                lines.append("   if(h_macd == INVALID_HANDLE) return INIT_FAILED;")
                lines.append("   ArraySetAsSeries(macdMainBuffer, true);")
                lines.append("   ArraySetAsSeries(macdSignalBuffer, true);")
            elif ind_type in ("bollinger_bands", "bb"):
                lines.append(f"   h_bb = iBands(_Symbol, PERIOD_CURRENT, InpBBPeriod, 0, InpBBStdDev, PRICE_CLOSE);")
                lines.append("   if(h_bb == INVALID_HANDLE) return INIT_FAILED;")
                lines.append("   ArraySetAsSeries(bbUpperBuffer, true);")
                lines.append("   ArraySetAsSeries(bbMiddleBuffer, true);")
                lines.append("   ArraySetAsSeries(bbLowerBuffer, true);")
            elif ind_type == "atr":
                lines.append(f"   h_atr = iATR(_Symbol, PERIOD_CURRENT, InpATRPeriod);")
                lines.append("   if(h_atr == INVALID_HANDLE) return INIT_FAILED;")
                lines.append("   ArraySetAsSeries(atrBuffer, true);")
            elif ind_type == "stochastic":
                lines.append(f"   h_stoch = iStochastic(_Symbol, PERIOD_CURRENT, InpStochK, InpStochD, InpStochSlowing, MODE_SMA, STO_LOWHIGH);")
                lines.append("   if(h_stoch == INVALID_HANDLE) return INIT_FAILED;")
                lines.append("   ArraySetAsSeries(stochKBuffer, true);")
                lines.append("   ArraySetAsSeries(stochDBuffer, true);")
            elif ind_type == "cci":
                lines.append(f"   h_cci = iCCI(_Symbol, PERIOD_CURRENT, InpCCIPeriod, PRICE_TYPICAL);")
                lines.append("   if(h_cci == INVALID_HANDLE) return INIT_FAILED;")
                lines.append("   ArraySetAsSeries(cciBuffer, true);")
            elif ind_type == "adx":
                lines.append(f"   h_adx = iADX(_Symbol, PERIOD_CURRENT, InpADXPeriod);")
                lines.append("   if(h_adx == INVALID_HANDLE) return INIT_FAILED;")
                lines.append("   ArraySetAsSeries(adxBuffer, true);")

        lines.append("")
        lines.append("   return INIT_SUCCEEDED;")
        lines.append("}")
        return "\n".join(lines) + "\n"

    def _generate_on_tick(self, indicators, entries, exits, rm) -> str:
        lines = [
            "//+------------------------------------------------------------------+",
            "//| Expert tick function                                             |",
            "//+------------------------------------------------------------------+",
            "void OnTick()",
            "{",
            "",
            "   // Check for new bar",
            "   datetime currentBarTime = iTime(_Symbol, PERIOD_CURRENT, 0);",
            "   if(currentBarTime == lastBarTime) return;",
            "   lastBarTime = currentBarTime;",
            "",
            "   // Refresh rates",
            "   symInfo.RefreshRates();",
            "",
            "   // Copy indicator data",
        ]

        for ind in indicators:
            ind_type = ind.get("type", "").lower()
            buf_name = {
                "sma": "smaBuffer", "ema": "emaBuffer", "rsi": "rsiBuffer",
                "macd": "macdMainBuffer", "bollinger_bands": "bbUpperBuffer", "bb": "bbUpperBuffer",
                "atr": "atrBuffer", "stochastic": "stochKBuffer", "cci": "cciBuffer", "adx": "adxBuffer",
            }.get(ind_type, f"{ind_type}Buffer")

            if ind_type == "macd":
                lines.append(f"   if(CopyBuffer(h_macd, 0, 0, 3, macdMainBuffer) <= 0) return;")
                lines.append(f"   if(CopyBuffer(h_macd, 1, 0, 3, macdSignalBuffer) <= 0) return;")
            else:
                handle = f"h_{ind_type}"
                lines.append(f"   if(CopyBuffer({handle}, 0, 0, 3, {buf_name}) <= 0) return;")

        lines.append("")
        lines.append("   // Check if we have an open position")
        lines.append("   bool hasPosition = false;")
        lines.append("   bool isLong = false;")
        lines.append("   for(int i = PositionsTotal() - 1; i >= 0; i--)")
        lines.append("   {")
        lines.append("      if(posInfo.SelectByIndex(i) && posInfo.Magic() == InpMagicNumber)")
        lines.append("      {")
        lines.append("         hasPosition = true;")
        lines.append("         isLong = posInfo.PositionType() == POSITION_TYPE_BUY;")
        lines.append("         break;")
        lines.append("      }")
        lines.append("   }")
        lines.append("")

        # Entry logic
        lines.append("   //--- Entry Logic")
        for entry in entries:
            sig_type = entry.get("type", "buy")
            condition = entry.get("condition", {})
            cond_code = self._generate_condition_code(condition, indicators)

            if sig_type == "buy":
                lines.append(f"   // BUY signal")
                lines.append(f"   if(!hasPosition && {cond_code})")
                lines.append("   {")
                lines.append("      double lotSize = CalculateLotSize(InpStopLoss);")
                lines.append("      double ask = symInfo.Ask();")
                lines.append("      double sl = InpStopLoss > 0 ? ask - InpStopLoss * _Point : 0;")
                lines.append("      double tp = InpTakeProfit > 0 ? ask + InpTakeProfit * _Point : 0;")
                lines.append("      trade.Buy(lotSize, _Symbol, ask, sl, tp);")
                lines.append("      return;")
                lines.append("   }")
            elif sig_type == "sell":
                lines.append(f"   // SELL signal")
                lines.append(f"   if(!hasPosition && {cond_code})")
                lines.append("   {")
                lines.append("      double lotSize = CalculateLotSize(InpStopLoss);")
                lines.append("      double bid = symInfo.Bid();")
                lines.append("      double sl = InpStopLoss > 0 ? bid + InpStopLoss * _Point : 0;")
                lines.append("      double tp = InpTakeProfit > 0 ? bid - InpTakeProfit * _Point : 0;")
                lines.append("      trade.Sell(lotSize, _Symbol, bid, sl, tp);")
                lines.append("      return;")
                lines.append("   }")

        # Exit logic
        if exits:
            lines.append("")
            lines.append("   //--- Exit Logic")
            for exit_sig in exits:
                condition = exit_sig.get("condition", {})
                cond_code = self._generate_condition_code(condition, indicators)
                lines.append(f"   if(hasPosition && {cond_code})")
                lines.append("   {")
                lines.append("      trade.PositionClose(_Symbol);")
                lines.append("      return;")
                lines.append("   }")

        # Trailing stop
        if rm.get("trailing_stop"):
            lines.append("")
            lines.append("   //--- Trailing Stop")
            lines.append("   if(hasPosition)")
            lines.append("   {")
            lines.append("      double trailPoints = InpTrailingStop * _Point;")
            lines.append("      for(int i = PositionsTotal() - 1; i >= 0; i--)")
            lines.append("      {")
            lines.append("         if(!posInfo.SelectByIndex(i) || posInfo.Magic() != InpMagicNumber) continue;")
            lines.append("         double openPrice = posInfo.PriceOpen();")
            lines.append("         if(isLong)")
            lines.append("         {")
            lines.append("            double newSL = symInfo.Bid() - trailPoints;")
            lines.append("            newSL = NormalizeDouble(newSL, _Digits);")
            lines.append("            if(newSL > posInfo.StopLoss() && newSL < symInfo.Bid() - symInfo.StopsLevel() * _Point)")
            lines.append("               trade.PositionModify(posInfo.Ticket(), newSL, posInfo.TakeProfit());")
            lines.append("         }")
            lines.append("         else")
            lines.append("         {")
            lines.append("            double newSL = symInfo.Ask() + trailPoints;")
            lines.append("            newSL = NormalizeDouble(newSL, _Digits);")
            lines.append("            if((newSL < posInfo.StopLoss() || posInfo.StopLoss() == 0) && newSL > symInfo.Ask() + symInfo.StopsLevel() * _Point)")
            lines.append("               trade.PositionModify(posInfo.Ticket(), newSL, posInfo.TakeProfit());")
            lines.append("         }")
            lines.append("      }")
            lines.append("   }")

        lines.append("}")
        return "\n".join(lines) + "\n"

    def _generate_on_deinit(self) -> str:
        return """
//+------------------------------------------------------------------+
//| Expert deinitialization function                                   |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
{
   IndicatorRelease(h_sma);
   IndicatorRelease(h_ema);
   IndicatorRelease(h_rsi);
   IndicatorRelease(h_macd);
   IndicatorRelease(h_bb);
   IndicatorRelease(h_atr);
   IndicatorRelease(h_stoch);
   IndicatorRelease(h_cci);
   IndicatorRelease(h_adx);
   ChartRedraw();
}
"""

    def _generate_condition_code(self, condition: dict, indicators: List[dict]) -> str:
        """Generate MQL5 condition code from condition group."""
        logic = condition.get("logic", "AND")
        conditions = condition.get("conditions", [])
        sub_groups = condition.get("sub_groups", [])

        parts = []
        for cond in conditions:
            left = cond.get("left_operand", "")
            op = cond.get("operator", "==")
            right = cond.get("right_operand", "")

            left_code = self._operand_to_mql(left, indicators)
            right_code = self._operand_to_mql(right, indicators)
            op_code = self._operator_to_mql(op)

            parts.append(f"({left_code} {op_code} {right_code})")

        for sg in sub_groups:
            parts.append(f"({self._generate_condition_code(sg, indicators)})")

        joiner = " && " if logic == "AND" else " || "
        return joiner.join(parts) if parts else "true"

    def _operand_to_mql(self, operand: str, indicators: List[dict]) -> str:
        """Convert operand string to MQL5 code."""
        operand = operand.strip().lower()

        if operand == "close":
            return "symInfo.Last()"
        elif operand == "open":
            return "iOpen(_Symbol, PERIOD_CURRENT, 1)"
        elif operand == "high":
            return "iHigh(_Symbol, PERIOD_CURRENT, 1)"
        elif operand == "low":
            return "iLow(_Symbol, PERIOD_CURRENT, 1)"

        # Indicator buffers
        if operand.startswith("sma("):
            return "smaBuffer[1]"
        elif operand.startswith("ema("):
            return "emaBuffer[1]"
        elif operand.startswith("rsi("):
            return "rsiBuffer[1]"
        elif operand == "macd_line":
            return "macdMainBuffer[1]"
        elif operand == "macd_signal":
            return "macdSignalBuffer[1]"
        elif operand == "upper_bb":
            return "bbUpperBuffer[1]"
        elif operand == "lower_bb":
            return "bbLowerBuffer[1]"
        elif operand == "middle_bb":
            return "bbMiddleBuffer[1]"
        elif operand.startswith("atr("):
            return "atrBuffer[1]"
        elif operand.startswith("stoch_k("):
            return "stochKBuffer[1]"
        elif operand.startswith("cci("):
            return "cciBuffer[1]"
        elif operand.startswith("adx("):
            return "adxBuffer[1]"

        # Try as number
        try:
            return str(float(operand))
        except ValueError:
            return operand

    def _operator_to_mql(self, op: str) -> str:
        mapping = {
            ">": ">", "<": "<", "==": "==", ">=": ">=", "<=": "<=",
            "crosses_above": ">",  # Simplified
            "crosses_below": "<",  # Simplified
        }
        return mapping.get(op, "==")

    def _generate_helper_functions(self) -> str:
        return """
//+------------------------------------------------------------------+
//| Calculate lot size based on risk percentage                       |
//+------------------------------------------------------------------+
double CalculateLotSize(double stopLossPoints)
{
   if(stopLossPoints <= 0 || InpRiskPercent <= 0)
      return InpLotSize;

   double accountBalance = AccountInfoDouble(ACCOUNT_BALANCE);
   double riskAmount = accountBalance * InpRiskPercent / 100.0;
   double tickValue = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_VALUE);
   double tickSize = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_SIZE);

   if(tickValue == 0 || tickSize == 0) return InpLotSize;

   double lotSize = riskAmount / (stopLossPoints * tickValue / tickSize);
   lotSize = NormalizeDouble(lotSize, 2);

   double minLot = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MIN);
   double maxLot = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MAX);
   double lotStep = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_STEP);

   lotSize = MathMax(minLot, lotSize);
   lotSize = MathMin(maxLot, lotSize);
   lotSize = MathFloor(lotSize / lotStep) * lotStep;

   return lotSize;
}

//+------------------------------------------------------------------+
//| Check if indicator value crossed above another                    |
//+------------------------------------------------------------------+
bool IsCrossedAbove(double &current[], double &previous[], int shift = 1)
{
   return current[shift] > previous[shift] && current[shift + 1] <= previous[shift + 1];
}

//+------------------------------------------------------------------+
//| Check if indicator value crossed below another                    |
//+------------------------------------------------------------------+
bool IsCrossedBelow(double &current[], double &previous[], int shift = 1)
{
   return current[shift] < previous[shift] && current[shift + 1] >= previous[shift + 1];
}
//+------------------------------------------------------------------+
"""
